class_name Constants

const ENVIRONMENT_LAYER = 1
const ENTITY_LAYER = 2
const INVINCIBLE_LAYER = 4
const ROOF_LAYER = 8
const PLAYER_LAYER = 16
const PLATFORM_LAYER = 32
const HIDING_BLOCK_LAYER = 64
const ENEMY_LAYER = 128
const BULLET_WALL_LAYER = 256
const INTERACTABLE_LAYER = 512
const PLAYER_BOUNDARY_LAYER = 1024

const MASTER_BUS_INDEX = 0
const MUSIC_BUS_INDEX = 1

const EPSILON = 0.000001
