class_name Constants

const ENVIRONMENT_LAYER = 1
const ENTITY_LAYER = 2
const INVINCIBLE_LAYER = 4
const ROOF_LAYER = 8
const PLAYER_LAYER = 16
const PLATFORM_LAYER_NUMBER = 6
const PLATFORM_LAYER_VALUE = 32

const EPSILON = 0.000001
